#!/usr/bin/env bash
#displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
file=$(ls)
for lsdfile in $file
do
	echo "$lsdfile" | cut -d "-" -f2
done
