#!/usr/bin/env bash
# A script that gives you information about the school file

FILE1="school"

if [ -e $FILE1 ]
then
	echo "school file exists"
	if [ -s $FILE1 ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f $FILE1 ]
	then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
